export const GENRE_LIST = [
  "Acid jazz",
  "Acoustic",
  "Alternative metal",
  "Alternative rock",
  "Ambient",
  "Big band",
  "Blues",
  "Classic rock",
  "Country rock",
  "Dance",
  "Disco",
  "Drum & bass",
  "Dubstep",
  "Electronic",
  "Euro dance",
  "Experimental",
  "Folk",
  "Funk",
  "Garage rock",
  "Glam metal",
  "Gospel",
  "Grime",
  "Grunge",
  "Guitarist",
  "Hard rock",
  "Heavy metal",
  "Hip-hop",
  "House",
  "Indie",
  "Industrial metal",
  "J-pop",
  "Jazz",
  "Latin",
  "Location",
  "Metal",
  "Musical",
  "New age",
  "New wave",
  "Nu metal",
  "Opera",
  "Orchestral",
  "Pop",
  "Pop-punk",
  "Pop-rock",
  "Post-rock",
  "Progressive metal",
  "Progressive rock",
  "Psychedelic rock",
  "Punk rock",
  "R&b",
  "Rap",
  "Reggae",
  "Rock",
  "Rock & roll",
  "Rockabilly",
  "Sludge metal",
  "Soft rock",
  "Soul",
  "Swing",
  "Symphonic metal",
  "Synthpop",
  "Techno",
  "Thrash metal",
  "Trance",
  "Trip hop",
  "Unclassified",
];
