export const LOCATION_LIST = [
  { location: "Boston, Massachusetts, USA" },
  { location: "Detroit" },
  { location: "Abbotsford, British Columbia, CA" },
  { location: "Abbott, Texas" },
  { location: "Abingdon, England" },
  { location: "Alabama, USA" },
  { location: "Albany, Georgia" },
  { location: "Alberta, Canada" },
  { location: "Alzey, Germany" },
  { location: "American" },
  { location: "Anaheim, USA" },
  { location: "Ann Arbor, Michigan, USA" },
  { location: "Antwerp, Belgium" },
  { location: "Arkansas, USA" },
  { location: "Athens, USA" },
  { location: "Atlanta, USA" },
  { location: "Attleboro, USA" },
  { location: "Bakersfield, California, USA" },
  { location: "Baltimore, Maryland, USA" },
  { location: "Banff, Aberdeenshire, Scotland, UK" },
  { location: "Barnwell, USA" },
  { location: "Barranquilla, Colombia" },
  { location: "Basildon, England" },
  { location: "Battle, England" },
  { location: "Bega, New South Wales, Australia" },
  { location: "Belfast, Northern Ireland" },
  { location: "Belleville, Ontario, Canada" },
  { location: "Birmingham, England" },
  { location: "Bishopbriggs, Scotland" },
  { location: "Boston, Massachusetts, USA" },
  { location: "Bremen, Germany" },
  { location: "Bristol, England" },
  { location: "Brooklyn, USA" },
  { location: "Budapest, Hungary" },
  { location: "Butler County, Alabama, USA" },
  { location: "California, USA" },
  { location: "Canada" },
  { location: "Charlemagne, QC, Canada" },
  { location: "Chicago, USA" },
  { location: "Cleveland, Ohio, USA" },
  { location: "Cologne, Germany" },
  { location: "Columbus, Ohio, USA" },
  { location: "Corsica, France" },
  { location: "Crawley, England" },
  { location: "Croix-des-Bouquets, Haiti" },
  { location: "Dallas, Texas, USA" },
  { location: "Dallas, USA" },
  { location: "Dartmoor, Devon, England" },
  { location: "Davyhulme, England, UK" },
  { location: "Dearborn, Michigan, USA" },
  { location: "Denver, Colorado, USA" },
  { location: "Detroit, Michigan, USA" },
  { location: "Detroit, USA" },
  { location: "Dover, England" },
  { location: "Dublin, Ireland" },
  { location: "Dundee, Scotland" },
  { location: "East Bay, California, USA" },
  { location: "East Finchley, England" },
  { location: "Eisenhüttenstadt, Germany" },
  { location: "Espoo, Finland" },
  { location: "Essex, England" },
  { location: "Essex, England, UK" },
  { location: "Eversley, England" },
  { location: "Florida, USA" },
  { location: "Fort Macleod, Canada" },
  { location: "Frankfurt, Germany" },
  { location: "Fukuoka, Japan" },
  { location: "Fullerton, California, USA" },
  { location: "Gainesville, USA" },
  { location: "Georgia, USA" },
  { location: "Germany" },
  { location: "Gothenburg, Sweden" },
  { location: "Guadalajara, Jalisco, Mexico" },
  { location: "Gweedore, Donegal, Ireland" },
  { location: "Halifax, England" },
  { location: "Hamburg, Germany" },
  { location: "Hannover, Germany" },
  { location: "Havering, London, England" },
  { location: "Hawaii, USA" },
  { location: "Hawthorne, California, USA" },
  { location: "Hemel Hempstead, England" },
  { location: "Houston, Texas, USA" },
  { location: "Houston, USA" },
  { location: "Ibadán, Nigeria" },
  { location: "Indiana, USA" },
  { location: "Iowa, USA" },
  { location: "Jacksonville, Florida, USA" },
  { location: "Jacksonville, Texas, U.S." },
  { location: "Jacksonville, USA" },
  { location: "Japan" },
  { location: "Kingsland, Arkansas, USA" },
  { location: "Kingston, Ontario, Canada" },
  { location: "Kutaisi, Georgian SSR, Soviet Union" },
  { location: "Kölliken, Switzerland" },
  { location: "Leeds, England" },
  { location: "Leeds, England, UK" },
  { location: "Leiden, Netherlands" },
  { location: "Leyton, England" },
  { location: "Liverpool, England" },
  { location: "Liverpool. England" },
  { location: "London, England" },
  { location: "London, England," },
  { location: "London, England, UK" },
  { location: "London, UK" },
  { location: "Los Angeles, CA" },
  { location: "Los Angeles, California, USA" },
  { location: "Los Angeles, Southern California" },
  { location: "Los Angeles, USA" },
  { location: "Lubbock, Texas, U.S." },
  { location: "Luton, England" },
  { location: "Lyon, France" },
  { location: "Madrid, Spain" },
  { location: "Manchester, England" },
  { location: "Manchester, England, UK" },
  { location: "Mangalia, Romania" },
  { location: "Massachusetts, USA" },
  { location: "McAlester, Oklahoma" },
  { location: "McComb, Mississippi, USA" },
  { location: "McComb, USA" },
  { location: "Mechanicsville, Virginia, USA" },
  { location: "Melbourne, Australia" },
  { location: "Memphis, Tennessee, USA" },
  { location: "Mexico" },
  { location: "Miami, Florida, USA" },
  { location: "Miami, USA" },
  { location: "Michigan, USA" },
  { location: "Middlesbrough, UK" },
  { location: "Minnesota, American" },
  { location: "Minnesota, USA" },
  { location: "Mississippi, USA" },
  { location: "Missouri, USA" },
  { location: "Modena, Italy" },
  { location: "Molfetta, BA" },
  { location: "Moseley, Birmingham, UK" },
  { location: "Muskegon, USA" },
  { location: "Münster" },
  { location: "New Haven, Connecticut, USA" },
  { location: "New Jersey, USA" },
  { location: "New Orleans, USA" },
  { location: "New York City, New York, USA" },
  { location: "New York City, USA" },
  { location: "New York, NY, USA" },
  { location: "New York, USA" },
  { location: "Newcastle, England, UK" },
  { location: "Nova Scotia, Canada" },
  { location: "Nuremberg, Germany" },
  { location: "Nutbush, USA" },
  { location: "Nyí\xadregyháza, Hungary" },
  { location: "Oakland, California, USA" },
  { location: "Ohio, USA" },
  { location: "Oklahoma, USA" },
  { location: "Ontario, Canada" },
  { location: "Oxford, England" },
  { location: "Palm Desert, California, USA" },
  { location: "Paris, France" },
  { location: "Pasadena, California, USA" },
  { location: "Payson, Utah, USA" },
  { location: "Pearsall,USA" },
  { location: "Pennsylvania, USA" },
  { location: "Perth, Australia" },
  { location: "Philadelphia, Pennsylvania, USA" },
  { location: "Pinner, Middlesex, England" },
  { location: "Pontypridd, Wales" },
  { location: "Port Arthur, USA" },
  { location: "Reykjavík, Iceland" },
  { location: "Ripley, Surrey, England" },
  { location: "Rome, Latium" },
  { location: "Romford, England" },
  { location: "Rugby, England" },
  { location: "Saint Ann, Jamaica" },
  { location: "Saint Michael, Barbados" },
  { location: "San Francisco, California, USA" },
  { location: "San Francisco, USA" },
  { location: "San Juan, Porto Rico" },
  { location: "San Juan, Puerto Rico" },
  { location: "Seattle, USA" },
  { location: "Seattle, Washington, USA" },
  { location: "Sevierville, Tennessee, USA" },
  { location: "Sheffield, England" },
  { location: "Shenandoah, USA" },
  { location: "Skewen, Neath, Wales" },
  { location: "South Africa" },
  { location: "South Fallsburg, New York, USA" },
  { location: "St Andrews, Scotland  " },
  { location: "Stockholm, Sweden" },
  { location: "Stoke-on-Trent, England" },
  { location: "Sunderland, England" },
  { location: "Sussex, England" },
  { location: "Teignmouth, England" },
  { location: "Tennessee, USA" },
  { location: "Texas, USA" },
  { location: "The Hague, Netherlands" },
  { location: "Tidworth, England" },
  { location: "Tiptonville, USA" },
  { location: "Tiszaújlak, Ukraine" },
  { location: "Tokyo, Japan" },
  { location: "Topeka, USA" },
  { location: "Toronto, Canada" },
  { location: "Tottenham, UK" },
  { location: "Tromsø, Norway" },
  { location: "Tulsa, USA" },
  { location: "Turin, Italy" },
  { location: "UK, USA" },
  { location: "USA" },
  { location: "Vancouver, Canada" },
  { location: "Vernon, Texas, USA" },
  { location: "Waddinxveen, Netherlands" },
  { location: "Washington, D.C., USA" },
  { location: "Washington, USA" },
  { location: "West Germany" },
  { location: "Woking, England" },
];
